### ISSUE TITLE
Creating labels in GitHub

### ISSUE THREAD

**Issue by AnnikaWeimer** [nathankw/pulsar_lims#225]

**Comment by twang15** [comment]
Hi Nathan,
 
Hope you are doing great!
 
These days, the Pulsar LIMS repo (https://github.com/nathankw/pulsar_lims) that you’ve created is being used intensively in our project.
Could you help us to add Annika as a contributor just like me so that she can create labels for issues, and assign them to new issues?
 
If possible, you may also grant me the privilege to do it on my own.
Thanks a lot!
 
Best,
Tao

**Comment by twang15** [comment]
Hey Annika,  just added you.
Tao – looks like you are a RoR pro now!
